import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { writeFileSync, existsSync } from "fs";
import { join } from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Optimize i18n bundle by pre-processing
const optimizeI18nBundle = () => {
	// 直接从 i18n-bundle.ts 读取内容进行优化
	const bundlePath = join(process.cwd(), 'src/i18n/i18n-bundle.ts');

	if (existsSync(bundlePath)) {
		console.log('✅ i18n bundle already exists, no need to regenerate');
	} else {
		console.warn('⚠️ i18n-bundle.ts not found, creating empty bundle');
		// 创建空的 i18n bundle 作为回退
		const emptyBundle = {
			'zh-CN': {},
			'en-US': {}
		};

		const bundleContent =
`// Auto-generated i18n bundle - DO NOT EDIT
export const I18N_BUNDLE = ${JSON.stringify(emptyBundle, null, 2)} as const;
export type I18nBundleType = typeof I18N_BUNDLE;
`;

		writeFileSync(bundlePath, bundleContent, 'utf8');
		console.log('✅ Empty i18n bundle created');
	}
};

// Pre-optimize i18n bundle if in production mode
if (prod) {
	optimizeI18nBundle();
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: prod ? "warning" : "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	minify: prod,
	// Optimization plugins
	define: {
		'process.env.NODE_ENV': `"${prod ? 'production' : 'development'}"`
	},
	// Bundle optimization
	platform: 'browser',
	drop: prod ? ['console', 'debugger'] : [],
	// Splitting configuration for better caching (disabled for plugin compatibility)
	splitting: false,
	// Code generation optimization
	keepNames: prod ? false : true,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
